#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfillment-controller
spec:
  selector:
    matchLabels:
      app: fulfillment-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: fulfillment-controller
    spec:
      serviceAccountName: fulfillment-controller
      volumes:
      - name: service-tls
        secret:
          secretName: fulfillment-service-tls
      - name: ca-cert
        secret:
          secretName: ca-key
      containers:
      - name: controller
        image: fulfillment-service
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: ca-cert
          mountPath: /usr/local/share/ca-certificates/ca.crt
          subPath: ca.crt
        command:
        - /usr/local/bin/fulfillment-service
        - start
        - controller
        - --log-level=debug
        - --log-headers=true
        - --log-bodies=true
        - --grpc-server-network=tcp
        - --grpc-server-address=fulfillment-api:8000
        - --token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - --ca-file=/usr/local/share/ca-certificates/ca.crt
