name: Kustomize Build

on:
  pull_request:
  push:
    branches-ignore:
      - "main"

concurrency:
  group: "kustomize-build"
  cancel-in-progress: true

jobs:
  kustomize-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install kustomize
        run: |
          curl -L -o kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.7.1/kustomize_v5.7.1_linux_amd64.tar.gz
          sudo tar -C /usr/local/bin -xf kustomize.tar.gz

      - name: Build kustomize modules
        run: |
          bash scripts/kustomize-build-all.sh
