apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-operator-base

# Common labels
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cloudkit-operator
    app.kubernetes.io/part-of: cloudkit
- pairs:
    cloudkit.openshift.io/project: cloudkit-operator

resources:
- crd.yaml
- deployment.yaml
- metrics-service.yaml
- rbac.yaml
- serviceaccount.yaml
