apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-base

resources:
  - shared
  - cloudkit-aap
  - cloudkit-operator

# Common annotations for all CloudKit components
commonAnnotations:
  cloudkit.io/organization: cloudkit

# Common labels for all CloudKit components  
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: cloudkit