AAP_HOSTNAME=https://dev-cloudkit-foobar.apps.hypershift1.nerc.mghpcc.org
AAP_VALIDATE_CERTS=false
AAP_ORGANIZATION_NAME=dev
AAP_PROJECT_NAME=bar
AAP_PROJECT_GIT_URI=https://github.com/innabox/cloudkit-aap
AAP_PROJECT_GIT_BRANCH=main
AAP_EE_IMAGE=ghcr.io/innabox/cloudkit-aap-ee
LICENSE_MANIFEST_PATH=/var/secrets/config-as-code-manifest/license.zip

