apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-aap-development

# Development environment annotations
commonAnnotations:
  environment: development

labels:
  - includeSelectors: true
    pairs:
      environment: development
      app.kubernetes.io/managed-by: kustomize

# kustomize will use files with the same name in base automatically.
resources:
  - ../../../base/cloudkit-aap

# Configuration generators
secretGenerator:
- name: config-as-code-ig
  literals:
  - AAP_HOSTNAME=https://dev-cloudkit-foobar.apps.hypershift1.nerc.mghpcc.org
  - AAP_VALIDATE_CERTS=false
  - AAP_ORGANIZATION_NAME=dev
  - AAP_PROJECT_NAME=cloudkit
  - AAP_PREFIX=dev
  - AAP_PROJECT_GIT_URI=https://github.com/innabox/cloudkit-aap
  - AAP_PROJECT_GIT_BRANCH=main
  - AAP_EE_IMAGE=quay.io/rh-ee-jkary/cloudkit-aap-ee:latest
  - AAP_INSTANCE_NAME=dev-cloudkit
  - LICENSE_MANIFEST_PATH=/var/secrets/config-as-code-manifest/license.zip
  - CLOUDKIT_TEMPLATE_COLLECTIONS=cloudkit.templates
  - CLOUDKIT_FULFILLMENT_SERVICE_URI=https://dev-fulfillment-api-foobar.apps.hypershift1.nerc.mghpcc.org
  options:
    disableNameSuffixHash: true
- name: config-as-code-manifest-ig
  files:
  - license.zip=License.zip
  options:
    disableNameSuffixHash: true


patches:
- patch: |-
    - op: replace
      path: /spec/containers/0/envFrom/0/secretRef/name
      value: dev-config-as-code-ig
    - op: replace
      path: /spec/containers/0/volumes/0/secret/secretName
      value: dev-config-as-code-manifest-ig
  target:
    kind: Job
    name: dev-app-bootstrap

- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/rh-ee-jkary/cloudkit-aap-ee:latest
    - op: replace
      path: /spec/template/spec/initContainers/0/env/0/value
      value: dev-cloudkit-foobar.apps.hypershift1.nerc.mghpcc.org
    - op: replace
      path: /spec/template/spec/initContainers/0/env/1/value
      value: dev-cloudkit-eda-foobar.apps.hypershift1.nerc.mghpcc.org
    - op: replace
      path: /spec/template/spec/initContainers/0/env/4/value
      value: dev-cloudkit-controller-foobar.apps.hypershift1.nerc.mghpcc.org
  target:
    kind: Job
    name: dev-aap-bootstrap
