apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-aap-development

# Development environment annotations
commonAnnotations:
  environment: development

labels:
  - includeSelectors: true
    pairs:
      environment: development
      app.kubernetes.io/managed-by: kustomize

resources:
  - ../../../base/cloudkit-aap

# Secret generators moved to parent development kustomization
secretGenerator:
- name: bar-config-as-code-ig
  envs:
  - config-as-code-ig.yaml
  options:
    disableNameSuffixHash: true
- name: bar-config-as-code-manifest-ig
  files:
  - license.zip=License.zip
  options:
    disableNameSuffixHash: true

replacements:
  - source:
      kind: Secret
      name: bar-config-as-code-ig
      fieldPath: metadata.name
    targets:
      - select:
          kind: Job
        fieldPaths:
          - spec.template.spec.containers.0.envFrom.0.secretRef.name
  #
  # Don't need this because secretGenerator handles it.
  #
  # - source:
  #     kind: Secret
  #     name: bar-config-as-code-manifest-ig
  #     fieldPath: metadata.name
  #   targets:
  #     - select:
  #         kind: Job
  #       fieldPaths:
  #         - spec.template.spec.volumes.[name=config-as-code-manifest-volume].secret.secretName
  #  
  # We cannot touch the secrets for AAP because then AAP can't update them.
  #
  # - source:
  #     kind: Secret
  #     name: cloudkit-admin-password
  #     fieldPath: metadata.name
  #   targets:
  #     - select:
  #         kind: Job
  #       fieldPaths:
  #         - spec.template.spec.containers.*.env.[name=AAP_PASSWORD].valueFrom.secretKeyRef.name
  # - source:
  #     kind: Secret
  #     name: cloudkit-eda-admin-password
  #     fieldPath: metadata.name
  #   targets:
  #     - select:
  #         kind: Job
  #       fieldPaths:
  #         - spec.template.spec.containers.*.env.[name=AAP_EDA_PASSWORD].valueFrom.secretKeyRef.name

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/innabox/cloudkit-aap-ee:latest
    - op: replace
      path: /spec/template/spec/initContainers/0/env/0/value
      value: dev-cloudkit-foobar.apps.hypershift1.nerc.mghpcc.org
    - op: replace
      path: /spec/template/spec/initContainers/0/env/1/value
      value: dev-cloudkit-eda-foobar.apps.hypershift1.nerc.mghpcc.org
    - op: replace
      path: /spec/template/spec/initContainers/0/env/4/value
      value: dev-cloudkit-controller-foobar.apps.hypershift1.nerc.mghpcc.org
  target:
    kind: Job
    name: aap-bootstrap
