apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudkit-aap-base

resources:
  - cloudkit_env.yaml
  - job.yaml

# Common annotations with naming metadata
commonAnnotations:
  cloudkit.io/organization: cloudkit
  cloudkit.io/project: aap
