apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    component: service

resources:
- certificate.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: fulfillment-service-config
  files:
  - files/rules.yaml
  
- name: fulfillment-service-envoy
  files:
  - files/envoy.yaml

- name: fulfillment-service-scripts
  files:
  - files/start-server.sh
  - files/test-server.sh
